name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted-ARMV8
    steps:
     
      - name: Check out repository code
        uses: |
          actions/checkout@v3
          ./.github/actions/git-action
      - name: Code test
        run: |
          python3 hello-world.py